name: "Github Annotations bot"
description: "Reads in a file and raises errors if there's any errors present"
author: "Fiona Hu"
branding:
  icon: "message-square"
  color: "blue"
inputs:
  result_path:
    description: "Path of JSON file containing results"
    required: true
  report_type:
    description: "Tool that this report is from"
    required: false
    default: "codeceptjs"

runs: 
  using: "node14"
  main: "src/index.js"