name: "Github Annotations bot"
description: "Reads in a file and raises errors if there's any errors present"
author: "Fiona Hu"
branding:
  icon: "message-square"
  color: "blue"
inputs:
  result_path:
    description: "Path of JSON file containing results"
    required: true
  codecept_input:
    description: "Whether or not this is a Codecept output"
    required: true

runs: 
  using: "node12"
  main: "src/index.js"