name: "Github Annotations bot"
description: "Annotates things (Come up with a better description before PR)"
author: "Fiona Hu"
branding:
  icon: "message-square"
  color: "blue"
inputs:
  resultPath:
    description: "Path of JSON file containing results"
    required: true
  codeceptOutput:
    description: "Whether or not this is a Codecept output"
    required: true
  pathDescriptor: 
    description: "If not a codecept output, this is a descriptor of where the tests will be"
    required: false

  using: "node12"
  main: "src/index.js"