
name: Annotation poster
on: [pull_request, repository_dispatch]

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run script
        uses: ./
        with:
          result_path: "./sampleCodeceptReport.json"