
name: Annotation poster
on: [pull_request, repository_dispatch]

env:
  node-version: 12.x

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: List directory
        run: |
          ls 
          pwd
      - name: Run script
        uses: ./
        with:
          resultPath: "./report.json"